import Team from "./interface/Team";

export const teamMember : Team = {
    "bakkum": {
        firstName: "Felix",
        lastName: "Bakkum",
        role: "Lead Developer",
        image: "./img/felix.jpg",
        html: 95,
        css: 77,
        uiUx: 44,
        react: 66,
        typescript: 66,
        node: 50,
    },
    "hagelin": {
        firstName: "Emil",
        lastName: "Hagelin",
        role: "CEO | Developer",
        image: "./img/felix.jpg",
        html: 95,
        css: 60,
        uiUx: 60,
        react: 60,
        typescript: 60,
        node: 60,
    },
    "körner": {
        firstName: "Edwin",
        lastName: "Körner",
        role: "Lead Designer",
        image: "./img/felix.jpg",
        html: 95,
        css: 60,
        uiUx: 60,
        react: 60,
        typescript: 60,
        node: 60,
    },
    "meiner": {
        firstName: "Christian",
        lastName: "Meiner",
        role: "COO | Designer",
        image: "./img/meiner.jpg",
        html: 95,
        css: 95,
        uiUx: 30,
        react: 65,
        typescript: 65,
        node: 45,
    },
    "rydin": {
        firstName: "Adrian",
        lastName: "Rydin",
        role: "Developer",
        image: "./img/felix.jpg",
        html: 95,
        css: 60,
        uiUx: 60,
        react: 60,
        typescript: 60,
        node: 60,
    }
}